services:      
  db:
    image: mysql:9.0
    restart: always
    environment:
      MYSQL_DATABASE: 'CinemaApp'
      MYSQL_USER: 'CinemaAppUser'
      MYSQL_PASSWORD: 'CinemaAppPassword'
      MYSQL_ROOT_PASSWORD: 'CinemaAppRootPassword'
    ports:
      - '3309:3306'
    volumes:
      - cinema-app-db:/var/lib/fms/mysql
volumes:
  cinema-app-db:
  
