services:      
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'CinemaApp'
      MYSQL_USER: 'CinemaAppUser'
      MYSQL_PASSWORD: 'CinemaAppPassword'
      MYSQL_ROOT_PASSWORD: 'CinemaAppRootPassword'
    ports:
      - '3309:3306'
    volumes:
      - bookmark-app-db:/var/lib/fms/mysql
volumes:
  bookmark-app-db:
  
