name: .NET

on:
  push:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install SSH agent and add private key
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    # Extract branch name
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    # Deploy to Ubuntu server via SSH
    - name: Deploy application
      run: |
        BRANCH=${{steps.extract_branch.outputs.branch}}
        APP_DIR="cinema/${BRANCH}/cinema"

        # Run the commands inline using ssh
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} \
        "cd $APP_DIR && \
        git pull origin $BRANCH && \
        cd .. && \
        docker stop ${BRANCH}-cinema.api-1 && \
        docker rm ${BRANCH}-cinema.api-1 && \
        docker compose up -d --build && \
        docker system prune -af"
